# Generated by Django 4.2.5 on 2023-09-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_veiculo_cor_alter_veiculo_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='models.cor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='models.modelo'),
        ),
    ]
